### ISSUE TITLE
mo-dump 导出订阅库数据报错“modump error: invalid input: table not found“

### ISSUE THREAD

**Issue by yangj1211** [matrixorigin/mo_dump#9]
<img width="800" alt="image" src="https://github.com/matrixorigin/mo_dump/assets/153493538/17d1fd12-cc69-4256-99a7-eca00e6534cd">

订阅者导出订阅库数据时报错“modump error: invalid input: table not found“

**Comment by dengn** [comment]
以前的modump可以跑通订阅库

**Comment by yangj1211** [comment]
fixed
